# yaml-language-server: $schema=https://json.schemastore.org/pre-commit-config.json
---
ci:
  autoupdate_schedule: quarterly

default_install_hook_types: ["pre-commit", "commit-msg"]
default_stages: ["pre-commit"]

repos:
  - repo: meta
    hooks:
      - id: identity

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: no-commit-to-branch
        args: ["--branch", "main"]
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: check-added-large-files
      - id: check-json
      - id: check-yaml
      - id: check-toml
      - id: check-ast
      - id: detect-private-key

  - repo: https://github.com/pre-commit-ci/pre-commit-ci-config
    rev: v1.6.1
    hooks:
      - id: check-pre-commit-ci-config

  # Conventional commits
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.4.0
    hooks:
      - id: conventional-pre-commit
        stages: ["commit-msg"]
        args:
          - build
          - chore
          - docs
          - feat
          - fix
          - perf
          - refactor
          - style
          - test
