# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
---
name: Publish Release (graceful test)
run-name: publish-release-graceful-test

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
      - run: uv build
      - uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
  publish-testpypi:
    name: Publish to Test PyPI
    runs-on: ubuntu-latest
    needs: ["build"]
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
      - uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      - run: |
          out=$(uv publish --index testpypi --token ${{ secrets.TEST_PYPI_TOKEN }} 2>&1)
          exitcode=$?

          if [[ $exitcode -eq 0 ]]; then
            echo "$out"
          elif [[ $out == "Publishing "*" files https://test.pypi.org/legacy/"*"error: Local file and index file do not match"* ]]; then
            echo "File already exists, skipping"
            exit 0
          else
            echo "$out" >&2
          fi
          exit $exitcode
